return (place_meeting(x, y + 1, oGround)) 
	or (place_meeting(x, y + 1, oSparseGround)) 
	or (place_meeting(x, y + 1, oBase))
	or (place_meeting(x, y + 1, oGroundCompleteLine))
	or (place_meeting(x, y + 1, oGroundLeftLine))
	or (place_meeting(x, y + 1, oGroundRightLine))
	or (place_meeting(x, y + 1, oGroundTopBottomLine))